### ISSUE TITLE
Installation on Manjaro?

### ISSUE THREAD

**Issue by br4nnigan** [hash-bang/Conkie#8]
failing at install already:

1. package is called "lm_sensors" not "lm-sensors"
2. npm audit reports 6 high vulnerabilities, ok we'll just ignore that
3. need to run `npx conkie` rather than `conkie` 
4. libgconf-2.so.4 missing, have to install package "gconf" 
5. now getting "(electron:159338): Pango-ERROR **: 10:37:13.962: Harfbuzz version too old (1.2.7)" and one step further to understanding why people like snapstore

**Comment by hash-bang** [comment]
@br4nnigan, thanks for those

1. Ah well spotted. I've corrected the README
2. Yeah best to. `npm audit` is horribly broken anyway and none of these warnings are relevent
3. Odd, must be new behaviour since the release so long ago
4. Updated README
5. Hmm. This is odd. As old as this project is it seems to work first time on my rig. I've added a package-lock file to see if its some weird new version of one of the downstream libraries causing the issue. Can you give it a go with the latest release?

**Comment by br4nnigan** [comment]
Hi,
notice I was just speaking for Manjaro. I don't know if the changes you made were necessary for Ubuntu.

Ok what I now did was clone this repository, npm install, npx conkie, didnt find conkie, ran npm run start, prompted me to install dependancy conkie, ok that was weird, anyway. Tried again, said again that libgconf was missing, well that's also weird given I had installed it when I last tried conkie. Anyway, went into add/remove software thing installed libg official repository, had conflicts or whatever and had to update 1.2gb of stuff, reboot, npm run start again, and voila haha, same error:

```
> conkie@1.2.17 start
> electron --enable-transparent-visuals --disable-gpu app.js

App threw an error during load
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at basename (path.js:1357:5)
    at Command.parse (/home/xxx/programs/Conkie/node_modules/commander/index.js:445:30)
    at Object.<anonymous> (/home/xxx/programs/Conkie/app.js:312:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (/home/xxx/programs/Conkie/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:280:12)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at basename (path.js:1357:5)
    at Command.parse (/home/xxx/programs/Conkie/node_modules/commander/index.js:445:30)
    at Object.<anonymous> (/home/xxx/programs/Conkie/app.js:312:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (/home/xxx/programs/Conkie/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:280:12)

(electron:3861): Pango-ERROR **: 21:16:08.697: Harfbuzz version too old (1.2.7)

```

ah well, at least we tried :)
